import { Link, useRouterState } from '@tanstack/react-router'
import { MapPin, Menu, Search, UserRound, X } from 'lucide-react'
import { useState } from 'react'
import { Brand } from './Brand'
import { Button } from '@/components/ui/button'
const links=[['/','Home'],['/events','Events'],['/events','Theatre']] as const
export function Header(){const [open,setOpen]=useState(false); const path=useRouterState({select:s=>s.location.pathname});return <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto grid h-16 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-4 sm:px-6 lg:flex lg:px-8"><Link to="/" aria-label="RangTix home"><Brand/></Link><nav className="mx-auto hidden items-center gap-1 lg:flex">{links.map(([to,label],i)=><Link key={label} to={to} className={`rounded-lg px-4 py-2 text-sm font-semibold transition-colors ${path===to&&i<2?'bg-accent text-primary':'text-muted-foreground hover:text-foreground'}`}>{label}</Link>)}</nav><div className="flex shrink-0 items-center gap-1"><Button variant="ghost" className="hidden sm:inline-flex"><MapPin/> Pune</Button><Button variant="ghost" size="icon" aria-label="Search" asChild><Link to="/events"><Search/></Link></Button><Button variant="ghost" size="icon" aria-label="Profile" asChild><Link to="/profile"><UserRound/></Link></Button><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Menu" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="border-t border-border bg-background px-4 py-3 lg:hidden">{links.slice(0,2).map(([to,label])=><Link key={label} to={to} onClick={()=>setOpen(false)} className="block rounded-lg px-3 py-3 font-semibold hover:bg-accent">{label}</Link>)}<Link to="/my-tickets" onClick={()=>setOpen(false)} className="block rounded-lg px-3 py-3 font-semibold hover:bg-accent">My Tickets</Link></nav>}</header>}
export function Footer(){return <footer className="border-t border-border bg-soft"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:grid-cols-3 sm:px-6 lg:px-8"><div><Brand/><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Thoughtful theatre discovery and simple ticket booking for Pune.</p></div><div><h3 className="font-bold">Explore</h3><div className="mt-3 grid gap-2 text-sm text-muted-foreground"><Link to="/events">Events</Link><Link to="/my-tickets">My Tickets</Link><Link to="/organizer">For Organizers</Link></div></div><div><h3 className="font-bold">Sample experience</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">All events, bookings and payments shown are fictional demonstration data.</p></div></div><div className="border-t border-border py-5 text-center text-xs text-muted-foreground">© 2026 RangTix. Frontend demonstration.</div></footer>}
export function SiteLayout({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
